Developer Instructions
vicb/flyxc pull request #186
Opened 2024-05-01 17:39 UTC by Murmele

2024-05-01 19:44 UTC, vicb requested changes
Thanks!

I added a few comments

2024-05-01 19:44 UTC, vicb commented on Developer.md
> +Copy `keys.ts.dist` to `keys.ts` and fill it out (there are two such files)
Would you mind expanding that to 2 bullets points with the full path to each of the file?

2024-05-01 19:44 UTC, vicb commented on Developer.md
> +`npx nx run-many -t build`
Not sure if this is needed - at least not for `npx nx dev`

2024-05-01 19:44 UTC, vicb commented on Developer.md
> +`npm run dev`
`npx nx dev` is better.

(Note that you can install nx globally with `npm i -g nx` so that you don't have to use `npx`)

2024-05-01 19:44 UTC, vicb commented on Developer.md
> +1) Cannot find name 'gtag'
Have you had issue with that?
I added some commits related to gtag and maybe you didn't `npm i` after you pulled the changes?

2024-05-01 19:44 UTC, vicb commented on libs/common/src/lib/keys.ts.dist
> +  BUY_ME_A_COFFEE_TOKEN = `...`,
good catch, I changed my local copy but forgot to update here

2024-05-14 13:57 UTC, Murmele commented
> Thanks!
> 
> I added a few comments

Thanks. I will check it out next weeks. Currently just the weather is good and flight planning must be done ^^

2024-05-14 14:54 UTC, vicb commented
> the weather is good and flight planning must be done ^^

Very valid reason... Have a nice flight :)

2024-06-10 18:54 UTC, vicb commented
We now have a CONTRIBUTING.md

2024-06-10 18:54 UTC, closed without merging